// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9KLA-BmMGGrAh_sEKVajNUAMuOaGokg',
    appId: '1:466892546022:web:7db86b825af5071fe40027',
    messagingSenderId: '466892546022',
    projectId: 'smilestreats',
    authDomain: 'smilestreats.firebaseapp.com',
    storageBucket: 'smilestreats.firebasestorage.app',
    measurementId: 'G-BTZ5026F3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApHk4gsUFsC-pT711j5RSFaQhlKRR_Q-g',
    appId: '1:466892546022:android:ba6444698809c898e40027',
    messagingSenderId: '466892546022',
    projectId: 'smilestreats',
    storageBucket: 'smilestreats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7gMzB1YNlQW9r3vzXUDK8u62_THbpBr0',
    appId: '1:466892546022:ios:80f9379efa855b3ae40027',
    messagingSenderId: '466892546022',
    projectId: 'smilestreats',
    storageBucket: 'smilestreats.firebasestorage.app',
    iosBundleId: 'com.willbefore.smilestreats',
  );
}
